apiVersion: v1
kind: Service
metadata:
  name: consul
  labels:
    name: consul
spec:
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: localhost:5000/consul:1.5.3
          ports:
            - containerPort: 8500