apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    name: eureka
spec:
  selector:
    app: eureka
  ports:
    - name: http
      port: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: flomesh/samples-discovery-server:latest
          ports:
            - containerPort: 8761