apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:latest
          ports:
            - containerPort: 2181
        - name: zookeeper-web
          image: tobilg/zookeeper-webui:latest
          ports:
            - containerPort: 8080
          env:
            - name: HTTP_PORT
              value: "8081"
            - name: ZK_DEFAULT_NODE
              value: 127.0.0.1:2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
