apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-application-yml
data:
  application.yml: |
    # 应用端口
    server:
      port: 14001
    grpc:
      server:
        port: 9091
      client:
        GLOBAL:
          negotiation-type: plaintext
          enable-keep-alive: true
          keep-alive-without-calls: true
    
    logging:
      level:
        root: INFO
        org.springframework.web.filter.CommonsRequestLoggingFilter: INFO
    
    management:
      endpoints:
        web:
          exposure:
            include: "health,info,prometheus"
    
    spring:
      application:
        # 应用名称
        name: bookstore
    
    eureka:
      client:
        registerWithEureka: true
        fetchRegistry: true
        gZipContent: false
        serviceUrl:
          defaultZone: http://eureka.default.svc.cluster.local:8761/eureka/
      instance:
        instance-id: ${spring.application.name}:${random.value}
        prefer-ip-address: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
      version: v2
  template:
    metadata:
      labels:
        app: bookstore
        version: v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "14001"
    spec:
      containers:
        - name: bookstore
          image: cybwan/springboot-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 14001
          env:
            - name: IDENTITY
              value: bookstore
            - name: EUREKA_INSTANCE_METADATAMAP_VERSION
              value: v1
            - name: JAVA_OPTS
              value: -Xms256M -Xmx512M
            - name: JAVA_TOOL_OPTIONS
              value: -javaagent:./opentelemetry-javaagent.jar -Dotel.resource.attributes=service.name=bookstore
          command: ['java']
          args: [
            "-Dotel.traces.exporter=logging",
            "-Dotel.metrics.exporter=none",
            "-Dotel.propagators=tracecontext,baggage,b3multi",
            "-jar",
            "bookstore-eureka.jar",
          ]
          volumeMounts:
            - mountPath: /config
              name: javacfg
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: javacfg
          configMap:
            name: bookstore-application-yml
            items:
              - key: "application.yml"
                path: "application.yml"