---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookthief
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookthief
      version: v1
  template:
    metadata:
      labels:
        app: bookthief
        version: v1
      annotations:
          prometheus.io/scrape: "true"
          prometheus.io/path: "/actuator/prometheus"
          prometheus.io/port: "14001"
    spec:
      containers:
        - name: bookthief
          image: addozhang/bookthief-eureka:latest
          ports:
            - containerPort: 14001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'eureka,prod'
            - name: IDENTITY
              value: bookthief
            - name: SPRING_CLOUD_CONSUL_DISCOVERY_TAGS
              value: "version=v1"
            - name: EUREKA_INSTANCE_METADATAMAP_VERSION
              value: v1
#            - name: SPRING_CLOUD_CONSUL_HOST
#              value: 'consul.default'
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 14001
            initialDelaySeconds: 60
            periodSeconds: 30
