---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstore
      version: v1
  template:
    metadata:
      labels:
        app: bookstore
        version: v1
    spec:
      containers:
        - name: bookstore
          image: addozhang/bookstore-dubbo:0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 20880
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'dubbo,prod'
            - name: IDENTITY
              value: bookstore
#            - name: DUBBO_REGISTRY_ADDRESS
#              value: 'zookeeper.default'
